# Generated by Django 3.2.8 on 2021-10-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fake',
        ),
    ]
