# Generated by Django 3.2.8 on 2021-10-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozapi', '0003_task_task_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
    ]
