# Generated by Django 3.2.8 on 2021-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozapi', '0004_remove_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(max_length=255),
        ),
    ]
