# Generated by Django 3.2.8 on 2021-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozapi', '0006_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(max_length=255, verbose_name='url'),
        ),
    ]
